[bridge]
server = http://127.0.0.1:8787
secret = d61a087bbd162d9692d0b96850ebd04a
name = PC-ACASA
agent = postsyt
# domenii permise prin bridge: * = ORICE domeniu public (router/localhost blocat oricum)
# vrei restrictie? pune lista, ex: allow = youtube.com,googleapis.com
allow = *
